-- Schéma VerifID (PostgreSQL). Appliqué au démarrage via spring.sql.init.mode=always.
-- Idempotent (IF NOT EXISTS + ALTER IF NOT EXISTS) : sûr à ré-exécuter à chaque boot.

-- =========================================================
-- Table : Clés API des organisations (issues du Kernel)
-- organization_id = UUID de l'organisation dans le Kernel
-- label           = nom lisible donné à la clé
-- api_key_hash    = SHA-256 de la clé brute (jamais stocker la clé en clair)
-- =========================================================
CREATE TABLE IF NOT EXISTS organization_api_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id VARCHAR(64)  NOT NULL,
    api_key_hash    VARCHAR(255) NOT NULL UNIQUE,
    label           VARCHAR(255),
    active          BOOLEAN      DEFAULT TRUE,
    created_at      TIMESTAMP    DEFAULT NOW()
);

-- =========================================================
-- Table : Logs de vérification de documents
-- platform_id = organization_id (UUID String) de l'appelant
-- api_key_id  = référence FK vers organization_api_keys.id (nullable pour Kafka)
-- =========================================================
CREATE TABLE IF NOT EXISTS verification_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id        VARCHAR(64),
    api_key_id         BIGINT REFERENCES organization_api_keys(id) ON DELETE SET NULL,
    date               TIMESTAMP,
    doc_type           VARCHAR(64),
    status             VARCHAR(32),
    reason             TEXT,
    confidence         DOUBLE PRECISION,
    processing_time_ms INTEGER,
    document_number    VARCHAR(128),
    holder_name        VARCHAR(255),
    date_of_birth      VARCHAR(32),
    issue_date         VARCHAR(32),
    expiry_date        VARCHAR(32),
    additional_fields  TEXT
);

-- =========================================================
-- Indexes
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_org_api_keys_org_id     ON organization_api_keys(organization_id);
CREATE INDEX IF NOT EXISTS idx_org_api_keys_hash        ON organization_api_keys(api_key_hash);
CREATE INDEX IF NOT EXISTS idx_verification_logs_org    ON verification_logs(platform_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_verification_logs_apikey ON verification_logs(api_key_id, date DESC);

-- =========================================================
-- Table : Administrateurs (Super Admins) pour l'accès aux stats
-- =========================================================
CREATE TABLE IF NOT EXISTS admins (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50)  NOT NULL DEFAULT 'SUPER_ADMIN',
    otp_code      VARCHAR(10),
    otp_expiry    TIMESTAMP,
    is_verified   BOOLEAN      DEFAULT FALSE,
    created_at    TIMESTAMP    DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email);
