-- Schéma VerifID (PostgreSQL). Appliqué au démarrage via spring.sql.init.mode=always.
-- Idempotent (IF NOT EXISTS + ALTER IF NOT EXISTS) : sûr à ré-exécuter à chaque boot.

-- =========================================================
-- Table : Organisations (Synchronisées depuis le Kernel)
-- =========================================================
CREATE TABLE IF NOT EXISTS organizations (
    id                       UUID PRIMARY KEY, -- UUID Kernel
    email                    VARCHAR(255) UNIQUE,
    name                     VARCHAR(255),
    display_name             VARCHAR(255),
    logo_uri                 TEXT,
    plan                     VARCHAR(50)  DEFAULT 'FREEMIUM',
    daily_verification_count INTEGER      DEFAULT 0,
    daily_count_reset_at     TIMESTAMP,
    created_at               TIMESTAMP    DEFAULT NOW(),
    last_synced_at           TIMESTAMP,
    
    -- API Key fields merged
    api_key_hash             VARCHAR(255) UNIQUE,
    api_key_label            VARCHAR(255),
    api_key_active           BOOLEAN      DEFAULT TRUE,
    api_key_created_at       TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_organizations_email ON organizations(email);
CREATE INDEX IF NOT EXISTS idx_organizations_apikey ON organizations(api_key_hash);

-- =========================================================
-- Table : Logs de vérification de documents
-- platform_id = organization_id (UUID String) de l'appelant
-- =========================================================
CREATE TABLE IF NOT EXISTS verification_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id        UUID REFERENCES organizations(id) ON DELETE SET NULL,
    date               TIMESTAMP,
    doc_type           VARCHAR(64),
    status             VARCHAR(32),
    reason             TEXT,
    confidence         DOUBLE PRECISION,
    processing_time_ms INTEGER,
    document_number    VARCHAR(128),
    holder_name        VARCHAR(255),
    date_of_birth      VARCHAR(32),
    issue_date         VARCHAR(32),
    expiry_date        VARCHAR(32),
    additional_fields  TEXT
);

-- =========================================================
-- Indexes
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_verification_logs_org    ON verification_logs(platform_id, date DESC);

-- =========================================================
-- Table : Administrateurs (Super Admins) pour l'accès aux stats
-- =========================================================
CREATE TABLE IF NOT EXISTS admins (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50)  NOT NULL DEFAULT 'SUPER_ADMIN',
    otp_code      VARCHAR(10),
    otp_expiry    TIMESTAMP,
    is_verified   BOOLEAN      DEFAULT FALSE,
    created_at    TIMESTAMP    DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email);
